### ISSUE TITLE
デバッグツールのbyebugをインストールできない

### ISSUE THREAD

**Issue by lvjiiiiu** [os1ma/performance-improvement-introduction-hands-on#17]
## 概要

デバッグツールのbyebugをインストールできない。

## 環境

macOS Big Sur
MacBook Air (Retina, 13-inch, 2020)

## 再現手順

試した手順は下記です。

### 手順：Gemfileに"byebug"を追加してコンテナ内でインストール

**1. ex01/ruby内のGemfileに"byebug"を追加**

answers/ex01/ruby/Gemfile
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "mysql2", "~> 0.5"
gem "byebug"
```

**2. コンテナへログイン(ruby)**

下記コマンドでコンテナへログイン
`docker-compose exec ruby bash`

**3. コンテナ内でGemfileがあるディレクトリまで移動**
```
cd exercises/ex01/ruby
```

**4. bundle install**
```
root@576906e2d3d3:/opt/performance-improvement-introduction-hands-on/exercises/ex01/ruby# bundle install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using bundler 2.2.22
Using mysql2 0.5.3
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Gemfile.lockへ追加なし
```
root@576906e2d3d3:/opt/performance-improvement-introduction-hands-on/exercises/ex01/ruby# cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    mysql2 (0.5.3)

PLATFORMS
  aarch64-linux
  x86_64-linux

DEPENDENCIES
  mysql2 (~> 0.5)

BUNDLED WITH
   2.2.22
```

**5. 試しにbyebugを使用してみる => NameErrorエラー**

試しにmain内でbyebugを使ってみる

exercises/ex01/ruby/main.rb
```
def main
  user_id = 1
  byebug
  ⋯

```
```
root@576906e2d3d3:/opt/performance-improvement-introduction-hands-on/exercises/ex01/ruby# ruby main_test.rb
Run options: --seed 6762

# Running:

E

Finished in 0.001988s, 502.9422 runs/s, 0.0000 assertions/s.

  1) Error:
SampleTest#test_main:
NameError: undefined local variable or method `byebug' for #<SampleTest:0x00007f104d4b6568 @NAME="test_main", @failures=[#<Minitest::UnexpectedError: Unexpected exception>], @assertions=0, @time=0.000145500001963228>

  byebug
  ^^^^^^
    /opt/performance-improvement-introduction-hands-on/exercises/ex01/ruby/main.rb:16:in `main'
    main_test.rb:7:in `block in test_main'
    main_test.rb:6:in `times'
    main_test.rb:6:in `test_main'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by os1ma** [comment]
@lvjiiiiu 

丁寧な手順をありがとうございます。

2点確認したいです。

### 1点目「4. bundle install」について

```ruby
gem "byebug"
```

という記述を追加されているのが

> answers/ex01/ruby/Gemfile

という、別のファイルのように見えます。

実行しようとしているのは

> exercises/ex01/ruby

のほうなので、exercises/ex01/ruby/Gemfileというファイルに

```ruby
gem "byebug"
```

と記述を追加して `bundle install` してみるようお願いします。

### 2点目「5. 試しにbyebugを使用してみる => NameErrorエラー」について

exercises/ex01/ruby/main.rbの最初に

```ruby
require 'byebug'
```

の記述は追加済みでしょうか？

もし追加されていなければ、この記述を追加して再度実行してみていただきたいです。

**Comment by lvjiiiiu** [comment]
@os1ma 
お忙しいところ、早速ご確認いただきましてありがとうございます。

(恐ろしいことに。。)ご指摘頂いたとおり、answersの方のGemfileへbyebugを追加しようとしていました。。

さらに下記の記述は完全に失念していたので`exercises/ex01/ruby/main.rb`の上部へ追加したところ、無事byebugの機能を利用することができました。
```ruby
require 'byebug'
```

お手数おかけしてしまったのが本当に申し訳ないくらいに、うっかりミス+初歩的なミスでしたが、
丁寧にご回答いただき大変ありがとうございました。

**Comment by os1ma** [comment]
@lvjiiiiu 
解決したようでよかったです！
こちらのIssueはクローズさせていただきます。
